name: Generate Profile Metrics

on:
  schedule:
    - cron: "0 12 * * *" # Runs once a day
  workflow_dispatch:     # Allows you to trigger it manually

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Base Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          theme: github-dark
